name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/5 * * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Your issue is stale AF'
        stale-pr-message: 'This PR is pretty stale bro'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 0
        days-before-close: 0
